overrides:
  '@types/react': 19.1.4
  '@types/react-dom': 19.1.5
  'glob@>=10.2.0 <10.5.0': 10.5.0
  'picomatch@<2.3.2': 2.3.2

allowBuilds:
  core-js: true
  sharp: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@posthog/core@1.35.1'
  - '@posthog/types@1.390.0'
  - posthog-js@1.390.2
  - brace-expansion@1.1.12
  - brace-expansion@2.0.2
  - '@eslint/plugin-kit@0.3.4'
  - js-yaml@4.1.1
  - minimatch@3.1.3
  - minimatch@9.0.6
  - minimatch@9.0.7
  - minimatch@3.1.4
  - ajv@6.14.0
  - flatted@3.4.0
  - flatted@3.4.2
  - brace-expansion@1.1.13
  - brace-expansion@2.0.3
  - yaml@2.8.3
  - postcss@8.5.10
  - js-yaml@4.1.2
