export const countries = [
  {
    name: 'United States',
    dialCode: '+1',
    code: 'US',
    continent: 'North America',
  },
  {
    name: 'Canada',
    dialCode: '+1',
    code: 'CA',
    continent: 'North America',
  },
  {
    name: 'Afghanistan',
    dialCode: '+93',
    code: 'AF',
    continent: 'Asia',
  },
  {
    name: 'Aland Islands',
    dialCode: '+358',
    code: 'AX',
    continent: 'Europe',
  },
  {
    name: 'Kosovo',
    dialCode: '+383',
    code: 'XK',
    continent: 'Europe',
  },
  {
    name: 'Albania',
    dialCode: '+355',
    code: 'AL',
    continent: 'Europe',
  },
  {
    name: 'Algeria',
    dialCode: '+213',
    code: 'DZ',
    continent: 'Africa',
  },
  {
    name: 'American Samoa',
    dialCode: '+1684',
    code: 'AS',
    continent: 'Oceania',
  },
  {
    name: 'Andorra',
    dialCode: '+376',
    code: 'AD',
    continent: 'Europe',
  },
  {
    name: 'Angola',
    dialCode: '+244',
    code: 'AO',
    continent: 'Africa',
  },
  {
    name: 'Anguilla',
    dialCode: '+1264',
    code: 'AI',
    continent: 'North America',
  },
  {
    name: 'Antarctica',
    dialCode: '+672',
    code: 'AQ',
    continent: 'Antarctica',
  },
  {
    name: 'Antigua and Barbuda',
    dialCode: '+1268',
    code: 'AG',
    continent: 'North America',
  },
  {
    name: 'Argentina',
    dialCode: '+54',
    code: 'AR',
    continent: 'South America',
  },
  {
    name: 'Armenia',
    dialCode: '+374',
    code: 'AM',
    continent: 'Asia',
  },
  {
    name: 'Aruba',
    dialCode: '+297',
    code: 'AW',
    continent: 'North America',
  },
  {
    name: 'Australia',
    dialCode: '+61',
    code: 'AU',
    continent: 'Oceania',
  },
  {
    name: 'Austria',
    dialCode: '+43',
    code: 'AT',
    continent: 'Europe',
  },
  {
    name: 'Azerbaijan',
    dialCode: '+994',
    code: 'AZ',
    continent: 'Asia',
  },
  {
    name: 'Bahamas',
    dialCode: '+1242',
    code: 'BS',
    continent: 'North America',
  },
  {
    name: 'Bahrain',
    dialCode: '+973',
    code: 'BH',
    continent: 'Asia',
  },
  {
    name: 'Bangladesh',
    dialCode: '+880',
    code: 'BD',
    continent: 'Asia',
  },
  {
    name: 'Barbados',
    dialCode: '+1246',
    code: 'BB',
    continent: 'North America',
  },
  {
    name: 'Belarus',
    dialCode: '+375',
    code: 'BY',
    continent: 'Europe',
  },
  {
    name: 'Belgium',
    dialCode: '+32',
    code: 'BE',
    continent: 'Europe',
  },
  {
    name: 'Belize',
    dialCode: '+501',
    code: 'BZ',
    continent: 'Central America',
  },
  {
    name: 'Benin',
    dialCode: '+229',
    code: 'BJ',
    continent: 'Africa',
  },
  {
    name: 'Bermuda',
    dialCode: '+1441',
    code: 'BM',
    continent: 'North America',
  },
  {
    name: 'Bhutan',
    dialCode: '+975',
    code: 'BT',
    continent: 'Asia',
  },
  {
    name: 'Bolivia, Plurinational State of',
    dialCode: '+591',
    code: 'BO',
    continent: 'South America',
  },
  {
    name: 'Bosnia and Herzegovina',
    dialCode: '+387',
    code: 'BA',
    continent: 'Europe',
  },
  {
    name: 'Botswana',
    dialCode: '+267',
    code: 'BW',
    continent: 'Africa',
  },
  {
    name: 'Brazil',
    dialCode: '+55',
    code: 'BR',
    continent: 'South America',
  },
  {
    name: 'British Indian Ocean Territory',
    dialCode: '+246',
    code: 'IO',
    continent: 'Africa',
  },
  {
    name: 'Brunei Darussalam',
    dialCode: '+673',
    code: 'BN',
    continent: 'Asia',
  },
  {
    name: 'Bulgaria',
    dialCode: '+359',
    code: 'BG',
    continent: 'Europe',
  },
  {
    name: 'Burkina Faso',
    dialCode: '+226',
    code: 'BF',
    continent: 'Africa',
  },
  {
    name: 'Burundi',
    dialCode: '+257',
    code: 'BI',
    continent: 'Africa',
  },
  {
    name: 'Cambodia',
    dialCode: '+855',
    code: 'KH',
    continent: 'Asia',
  },
  {
    name: 'Cameroon',
    dialCode: '+237',
    code: 'CM',
    continent: 'Africa',
  },

  {
    name: 'Cape Verde',
    dialCode: '+238',
    code: 'CV',
    continent: 'Africa',
  },
  {
    name: 'Cayman Islands',
    dialCode: '+ 345',
    code: 'KY',
    continent: 'North America',
  },
  {
    name: 'Central African Republic',
    dialCode: '+236',
    code: 'CF',
    continent: 'Africa',
  },
  {
    name: 'Chad',
    dialCode: '+235',
    code: 'TD',
    continent: 'Africa',
  },
  {
    name: 'Chile',
    dialCode: '+56',
    code: 'CL',
    continent: 'South America',
  },
  {
    name: 'China',
    dialCode: '+86',
    code: 'CN',
    continent: 'Asia',
  },
  {
    name: 'Christmas Island',
    dialCode: '+61',
    code: 'CX',
    continent: 'Oceania',
  },
  {
    name: 'Cocos (Keeling) Islands',
    dialCode: '+61',
    code: 'CC',
    continent: 'Oceania',
  },
  {
    name: 'Colombia',
    dialCode: '+57',
    code: 'CO',
    continent: 'South America',
  },
  {
    name: 'Comoros',
    dialCode: '+269',
    code: 'KM',
    continent: 'Africa',
  },
  {
    name: 'Congo',
    dialCode: '+242',
    code: 'CG',
    continent: 'Africa',
  },
  {
    name: 'Congo, The Democratic Republic of the Congo',
    dialCode: '+243',
    code: 'CD',
    continent: 'Africa',
  },
  {
    name: 'Cook Islands',
    dialCode: '+682',
    code: 'CK',
    continent: 'Oceania',
  },
  {
    name: 'Costa Rica',
    dialCode: '+506',
    code: 'CR',
    continent: 'Central America',
  },
  {
    name: "Cote d'Ivoire",
    dialCode: '+225',
    code: 'CI',
    continent: 'Africa',
  },
  {
    name: 'Croatia',
    dialCode: '+385',
    code: 'HR',
    continent: 'Europe',
  },
  {
    name: 'Cuba',
    dialCode: '+53',
    code: 'CU',
    continent: 'North America',
  },
  {
    name: 'Cyprus',
    dialCode: '+357',
    code: 'CY',
    continent: 'Asia',
  },
  {
    name: 'Czech Republic',
    dialCode: '+420',
    code: 'CZ',
    continent: 'Europe',
  },
  {
    name: 'Denmark',
    dialCode: '+45',
    code: 'DK',
    continent: 'Europe',
  },
  {
    name: 'Djibouti',
    dialCode: '+253',
    code: 'DJ',
    continent: 'Africa',
  },
  {
    name: 'Dominica',
    dialCode: '+1767',
    code: 'DM',
    continent: 'North America',
  },
  {
    name: 'Dominican Republic',
    dialCode: '+1849',
    code: 'DO',
    continent: 'North America',
  },
  {
    name: 'Ecuador',
    dialCode: '+593',
    code: 'EC',
    continent: 'South America',
  },
  {
    name: 'Egypt',
    dialCode: '+20',
    code: 'EG',
    continent: 'Africa',
  },
  {
    name: 'El Salvador',
    dialCode: '+503',
    code: 'SV',
    continent: 'Central America',
  },
  {
    name: 'Equatorial Guinea',
    dialCode: '+240',
    code: 'GQ',
    continent: 'Africa',
  },
  {
    name: 'Eritrea',
    dialCode: '+291',
    code: 'ER',
    continent: 'Africa',
  },
  {
    name: 'Estonia',
    dialCode: '+372',
    code: 'EE',
    continent: 'Europe',
  },
  {
    name: 'Ethiopia',
    dialCode: '+251',
    code: 'ET',
    continent: 'Africa',
  },
  {
    name: 'Falkland Islands (Malvinas)',
    dialCode: '+500',
    code: 'FK',
    continent: 'South America',
  },
  {
    name: 'Faroe Islands',
    dialCode: '+298',
    code: 'FO',
    continent: 'Europe',
  },
  {
    name: 'Fiji',
    dialCode: '+679',
    code: 'FJ',
    continent: 'Oceania',
  },
  {
    name: 'Finland',
    dialCode: '+358',
    code: 'FI',
    continent: 'Europe',
  },
  {
    name: 'France',
    dialCode: '+33',
    code: 'FR',
    continent: 'Europe',
  },
  {
    name: 'French Guiana',
    dialCode: '+594',
    code: 'GF',
    continent: 'South America',
  },
  {
    name: 'French Polynesia',
    dialCode: '+689',
    code: 'PF',
    continent: 'Oceania',
  },
  {
    name: 'Gabon',
    dialCode: '+241',
    code: 'GA',
    continent: 'Africa',
  },
  {
    name: 'Gambia',
    dialCode: '+220',
    code: 'GM',
    continent: 'Africa',
  },
  {
    name: 'Georgia',
    dialCode: '+995',
    code: 'GE',
    continent: 'Asia',
  },
  {
    name: 'Germany',
    dialCode: '+49',
    code: 'DE',
    continent: 'Europe',
  },
  {
    name: 'Ghana',
    dialCode: '+233',
    code: 'GH',
    continent: 'Africa',
  },
  {
    name: 'Gibraltar',
    dialCode: '+350',
    code: 'GI',
    continent: 'Europe',
  },
  {
    name: 'Greece',
    dialCode: '+30',
    code: 'GR',
    continent: 'Europe',
  },
  {
    name: 'Greenland',
    dialCode: '+299',
    code: 'GL',
    continent: 'North America',
  },
  {
    name: 'Grenada',
    dialCode: '+1473',
    code: 'GD',
    continent: 'North America',
  },
  {
    name: 'Guadeloupe',
    dialCode: '+590',
    code: 'GP',
    continent: 'South America',
  },
  {
    name: 'Guam',
    dialCode: '+1671',
    code: 'GU',
    continent: 'Oceania',
  },
  {
    name: 'Guatemala',
    dialCode: '+502',
    code: 'GT',
    continent: 'Central America',
  },
  {
    name: 'Guernsey',
    dialCode: '+44',
    code: 'GG',
    continent: 'Europe',
  },
  {
    name: 'Guinea',
    dialCode: '+224',
    code: 'GN',
    continent: 'Africa',
  },
  {
    name: 'Guinea-Bissau',
    dialCode: '+245',
    code: 'GW',
    continent: 'Africa',
  },
  {
    name: 'Guyana',
    dialCode: '+595',
    code: 'GY',
    continent: 'South America',
  },
  {
    name: 'Haiti',
    dialCode: '+509',
    code: 'HT',
    continent: 'North America',
  },
  {
    name: 'Holy See (Vatican City State)',
    dialCode: '+379',
    code: 'VA',
    continent: 'Europe',
  },
  {
    name: 'Honduras',
    dialCode: '+504',
    code: 'HN',
    continent: 'Central America',
  },
  {
    name: 'Hong Kong',
    dialCode: '+852',
    code: 'HK',
    continent: 'Asia',
  },
  {
    name: 'Hungary',
    dialCode: '+36',
    code: 'HU',
    continent: 'Europe',
  },
  {
    name: 'Iceland',
    dialCode: '+354',
    code: 'IS',
    continent: 'Europe',
  },
  {
    name: 'India',
    dialCode: '+91',
    code: 'IN',
    continent: 'Asia',
  },
  {
    name: 'Indonesia',
    dialCode: '+62',
    code: 'ID',
    continent: 'Asia',
  },
  {
    name: 'Iran, Islamic Republic of Persian Gulf',
    dialCode: '+98',
    code: 'IR',
    continent: 'Asia',
  },
  {
    name: 'Iraq',
    dialCode: '+964',
    code: 'IQ',
    continent: 'Asia',
  },
  {
    name: 'Ireland',
    dialCode: '+353',
    code: 'IE',
    continent: 'Europe',
  },
  {
    name: 'Isle of Man',
    dialCode: '+44',
    code: 'IM',
    continent: 'Europe',
  },
  {
    name: 'Israel',
    dialCode: '+972',
    code: 'IL',
    continent: 'Asia',
  },
  {
    name: 'Italy',
    dialCode: '+39',
    code: 'IT',
    continent: 'Europe',
  },
  {
    name: 'Jamaica',
    dialCode: '+1876',
    code: 'JM',
    continent: 'North America',
  },
  {
    name: 'Japan',
    dialCode: '+81',
    code: 'JP',
    continent: 'Asia',
  },
  {
    name: 'Jersey',
    dialCode: '+44',
    code: 'JE',
    continent: 'Europe',
  },
  {
    name: 'Jordan',
    dialCode: '+962',
    code: 'JO',
    continent: 'Asia',
  },
  {
    name: 'Kazakhstan',
    dialCode: '+7',
    code: 'KZ',
    continent: 'Asia',
  },
  {
    name: 'Kenya',
    dialCode: '+254',
    code: 'KE',
    continent: 'Africa',
  },
  {
    name: 'Kiribati',
    dialCode: '+686',
    code: 'KI',
    continent: 'Oceania',
  },
  {
    name: "Korea, Democratic People's Republic of Korea",
    dialCode: '+850',
    code: 'KP',
    continent: 'Asia',
  },
  {
    name: 'Korea, Republic of South Korea',
    dialCode: '+82',
    code: 'KR',
    continent: 'Asia',
  },
  {
    name: 'Kuwait',
    dialCode: '+965',
    code: 'KW',
    continent: 'Asia',
  },
  {
    name: 'Kyrgyzstan',
    dialCode: '+996',
    code: 'KG',
    continent: 'Asia',
  },
  {
    name: 'Laos',
    dialCode: '+856',
    code: 'LA',
    continent: 'Asia',
  },
  {
    name: 'Latvia',
    dialCode: '+371',
    code: 'LV',
    continent: 'Europe',
  },
  {
    name: 'Lebanon',
    dialCode: '+961',
    code: 'LB',
    continent: 'Asia',
  },
  {
    name: 'Lesotho',
    dialCode: '+266',
    code: 'LS',
    continent: 'Africa',
  },
  {
    name: 'Liberia',
    dialCode: '+231',
    code: 'LR',
    continent: 'Africa',
  },
  {
    name: 'Libyan Arab Jamahiriya',
    dialCode: '+218',
    code: 'LY',
    continent: 'Africa',
  },
  {
    name: 'Liechtenstein',
    dialCode: '+423',
    code: 'LI',
    continent: 'Europe',
  },
  {
    name: 'Lithuania',
    dialCode: '+370',
    code: 'LT',
    continent: 'Europe',
  },
  {
    name: 'Luxembourg',
    dialCode: '+352',
    code: 'LU',
    continent: 'Europe',
  },
  {
    name: 'Macao',
    dialCode: '+853',
    code: 'MO',
    continent: 'Asia',
  },
  {
    name: 'Macedonia',
    dialCode: '+389',
    code: 'MK',
    continent: 'Europe',
  },
  {
    name: 'Madagascar',
    dialCode: '+261',
    code: 'MG',
    continent: 'Africa',
  },
  {
    name: 'Malawi',
    dialCode: '+265',
    code: 'MW',
    continent: 'Africa',
  },
  {
    name: 'Malaysia',
    dialCode: '+60',
    code: 'MY',
    continent: 'Asia',
  },
  {
    name: 'Maldives',
    dialCode: '+960',
    code: 'MV',
    continent: 'Asia',
  },
  {
    name: 'Mali',
    dialCode: '+223',
    code: 'ML',
    continent: 'Africa',
  },
  {
    name: 'Malta',
    dialCode: '+356',
    code: 'MT',
    continent: 'Europe',
  },
  {
    name: 'Marshall Islands',
    dialCode: '+692',
    code: 'MH',
    continent: 'Oceania',
  },
  {
    name: 'Martinique',
    dialCode: '+596',
    code: 'MQ',
    continent: 'South America',
  },
  {
    name: 'Mauritania',
    dialCode: '+222',
    code: 'MR',
    continent: 'Africa',
  },
  {
    name: 'Mauritius',
    dialCode: '+230',
    code: 'MU',
    continent: 'Africa',
  },
  {
    name: 'Mayotte',
    dialCode: '+262',
    code: 'YT',
    continent: 'Africa',
  },
  {
    name: 'Mexico',
    dialCode: '+52',
    code: 'MX',
    continent: 'North America',
  },
  {
    name: 'Micronesia, Federated States of Micronesia',
    dialCode: '+691',
    code: 'FM',
    continent: 'Oceania',
  },
  {
    name: 'Moldova',
    dialCode: '+373',
    code: 'MD',
    continent: 'Europe',
  },
  {
    name: 'Monaco',
    dialCode: '+377',
    code: 'MC',
    continent: 'Europe',
  },
  {
    name: 'Mongolia',
    dialCode: '+976',
    code: 'MN',
    continent: 'Asia',
  },
  {
    name: 'Montenegro',
    dialCode: '+382',
    code: 'ME',
    continent: 'Europe',
  },
  {
    name: 'Montserrat',
    dialCode: '+1664',
    code: 'MS',
    continent: 'North America',
  },
  {
    name: 'Morocco',
    dialCode: '+212',
    code: 'MA',
    continent: 'Africa',
  },
  {
    name: 'Mozambique',
    dialCode: '+258',
    code: 'MZ',
    continent: 'Africa',
  },
  {
    name: 'Myanmar',
    dialCode: '+95',
    code: 'MM',
    continent: 'Asia',
  },
  {
    name: 'Namibia',
    dialCode: '+264',
    code: 'NA',
    continent: 'Africa',
  },
  {
    name: 'Nauru',
    dialCode: '+674',
    code: 'NR',
    continent: 'Oceania',
  },
  {
    name: 'Nepal',
    dialCode: '+977',
    code: 'NP',
    continent: 'Asia',
  },
  {
    name: 'Netherlands',
    dialCode: '+31',
    code: 'NL',
    continent: 'Europe',
  },
  {
    name: 'Netherlands Antilles',
    dialCode: '+599',
    code: 'AN',
    continent: 'South America',
  },
  {
    name: 'Bonaire',
    dialCode: '+599',
    code: 'BQ',
    continent: 'South America',
  },
  {
    name: 'Curaçao',
    dialCode: '+599',
    code: 'CW',
    continent: 'South America',
  },
  {
    name: 'New Caledonia',
    dialCode: '+687',
    code: 'NC',
    continent: 'Oceania',
  },
  {
    name: 'New Zealand',
    dialCode: '+64',
    code: 'NZ',
    continent: 'Oceania',
  },
  {
    name: 'Nicaragua',
    dialCode: '+505',
    code: 'NI',
    continent: 'Central America',
  },
  {
    name: 'Niger',
    dialCode: '+227',
    code: 'NE',
    continent: 'Africa',
  },
  {
    name: 'Nigeria',
    dialCode: '+234',
    code: 'NG',
    continent: 'Africa',
  },
  {
    name: 'Niue',
    dialCode: '+683',
    code: 'NU',
    continent: 'Oceania',
  },
  {
    name: 'Norfolk Island',
    dialCode: '+672',
    code: 'NF',
    continent: 'Oceania',
  },
  {
    name: 'Northern Mariana Islands',
    dialCode: '+1670',
    code: 'MP',
    continent: 'Oceania',
  },
  {
    name: 'Norway',
    dialCode: '+47',
    code: 'NO',
    continent: 'Europe',
  },
  {
    name: 'Oman',
    dialCode: '+968',
    code: 'OM',
    continent: 'Asia',
  },
  {
    name: 'Pakistan',
    dialCode: '+92',
    code: 'PK',
    continent: 'Asia',
  },
  {
    name: 'Palau',
    dialCode: '+680',
    code: 'PW',
    continent: 'Oceania',
  },
  {
    name: 'Palestinian Territory, Occupied',
    dialCode: '+970',
    code: 'PS',
    continent: 'Asia',
  },
  {
    name: 'Panama',
    dialCode: '+507',
    code: 'PA',
    continent: 'Central America',
  },
  {
    name: 'Papua New Guinea',
    dialCode: '+675',
    code: 'PG',
    continent: 'Oceania',
  },
  {
    name: 'Paraguay',
    dialCode: '+595',
    code: 'PY',
    continent: 'South America',
  },
  {
    name: 'Peru',
    dialCode: '+51',
    code: 'PE',
    continent: 'South America',
  },
  {
    name: 'Philippines',
    dialCode: '+63',
    code: 'PH',
    continent: 'Asia',
  },
  {
    name: 'Pitcairn',
    dialCode: '+872',
    code: 'PN',
    continent: 'Oceania',
  },
  {
    name: 'Poland',
    dialCode: '+48',
    code: 'PL',
    continent: 'Europe',
  },
  {
    name: 'Portugal',
    dialCode: '+351',
    code: 'PT',
    continent: 'Europe',
  },
  {
    name: 'Puerto Rico',
    dialCode: '+1939',
    code: 'PR',
    continent: 'North America',
  },
  {
    name: 'Qatar',
    dialCode: '+974',
    code: 'QA',
    continent: 'Asia',
  },
  {
    name: 'Romania',
    dialCode: '+40',
    code: 'RO',
    continent: 'Europe',
  },
  {
    name: 'Russia',
    dialCode: '+7',
    code: 'RU',
    continent: 'Europe',
  },
  {
    name: 'Rwanda',
    dialCode: '+250',
    code: 'RW',
    continent: 'Africa',
  },
  {
    name: 'Reunion',
    dialCode: '+262',
    code: 'RE',
    continent: 'Africa',
  },
  {
    name: 'Saint Barthelemy',
    dialCode: '+590',
    code: 'BL',
    continent: 'South America',
  },
  {
    name: 'Saint Helena, Ascension and Tristan Da Cunha',
    dialCode: '+290',
    code: 'SH',
    continent: 'Africa',
  },
  {
    name: 'Saint Kitts and Nevis',
    dialCode: '+1869',
    code: 'KN',
    continent: 'North America',
  },
  {
    name: 'Saint Lucia',
    dialCode: '+1758',
    code: 'LC',
    continent: 'North America',
  },
  {
    name: 'Saint Martin',
    dialCode: '+590',
    code: 'MF',
    continent: 'South America',
  },
  {
    name: 'Saint Pierre and Miquelon',
    dialCode: '+508',
    code: 'PM',
    continent: 'North America',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    dialCode: '+1784',
    code: 'VC',
    continent: 'North America',
  },
  {
    name: 'Samoa',
    dialCode: '+685',
    code: 'WS',
    continent: 'Oceania',
  },
  {
    name: 'San Marino',
    dialCode: '+378',
    code: 'SM',
    continent: 'Europe',
  },
  {
    name: 'Sao Tome and Principe',
    dialCode: '+239',
    code: 'ST',
    continent: 'Africa',
  },
  {
    name: 'Saudi Arabia',
    dialCode: '+966',
    code: 'SA',
    continent: 'Asia',
  },
  {
    name: 'Senegal',
    dialCode: '+221',
    code: 'SN',
    continent: 'Africa',
  },
  {
    name: 'Serbia',
    dialCode: '+381',
    code: 'RS',
    continent: 'Europe',
  },
  {
    name: 'Seychelles',
    dialCode: '+248',
    code: 'SC',
    continent: 'Africa',
  },
  {
    name: 'Sierra Leone',
    dialCode: '+232',
    code: 'SL',
    continent: 'Africa',
  },
  {
    name: 'Singapore',
    dialCode: '+65',
    code: 'SG',
    continent: 'Asia',
  },
  {
    name: 'Slovakia',
    dialCode: '+421',
    code: 'SK',
    continent: 'Europe',
  },
  {
    name: 'Slovenia',
    dialCode: '+386',
    code: 'SI',
    continent: 'Europe',
  },
  {
    name: 'Solomon Islands',
    dialCode: '+677',
    code: 'SB',
    continent: 'Oceania',
  },
  {
    name: 'Somalia',
    dialCode: '+252',
    code: 'SO',
    continent: 'Africa',
  },
  {
    name: 'South Africa',
    dialCode: '+27',
    code: 'ZA',
    continent: 'Africa',
  },
  {
    name: 'South Sudan',
    dialCode: '+211',
    code: 'SS',
    continent: 'Africa',
  },
  {
    name: 'South Georgia and the South Sandwich Islands',
    dialCode: '+500',
    code: 'GS',
    continent: 'South America',
  },
  {
    name: 'Spain',
    dialCode: '+34',
    code: 'ES',
    continent: 'Europe',
  },
  {
    name: 'Sri Lanka',
    dialCode: '+94',
    code: 'LK',
    continent: 'Asia',
  },
  {
    name: 'Sudan',
    dialCode: '+249',
    code: 'SD',
    continent: 'Africa',
  },
  {
    name: 'Suriname',
    dialCode: '+597',
    code: 'SR',
    continent: 'South America',
  },
  {
    name: 'Svalbard and Jan Mayen',
    dialCode: '+47',
    code: 'SJ',
    continent: 'Europe',
  },
  {
    name: 'Swaziland',
    dialCode: '+268',
    code: 'SZ',
    continent: 'Africa',
  },
  {
    name: 'Sweden',
    dialCode: '+46',
    code: 'SE',
    continent: 'Europe',
  },
  {
    name: 'Switzerland',
    dialCode: '+41',
    code: 'CH',
    continent: 'Europe',
  },
  {
    name: 'Syrian Arab Republic',
    dialCode: '+963',
    code: 'SY',
    continent: 'Asia',
  },
  {
    name: 'Taiwan',
    dialCode: '+886',
    code: 'TW',
    continent: 'Asia',
  },
  {
    name: 'Tajikistan',
    dialCode: '+992',
    code: 'TJ',
    continent: 'Asia',
  },
  {
    name: 'Tanzania, United Republic of Tanzania',
    dialCode: '+255',
    code: 'TZ',
    continent: 'Africa',
  },
  {
    name: 'Thailand',
    dialCode: '+66',
    code: 'TH',
    continent: 'Asia',
  },
  {
    name: 'Timor-Leste',
    dialCode: '+670',
    code: 'TL',
    continent: 'Asia',
  },
  {
    name: 'Togo',
    dialCode: '+228',
    code: 'TG',
    continent: 'Africa',
  },
  {
    name: 'Tokelau',
    dialCode: '+690',
    code: 'TK',
    continent: 'Oceania',
  },
  {
    name: 'Tonga',
    dialCode: '+676',
    code: 'TO',
    continent: 'Oceania',
  },
  {
    name: 'Trinidad and Tobago',
    dialCode: '+1868',
    code: 'TT',
    continent: 'North America',
  },
  {
    name: 'Tunisia',
    dialCode: '+216',
    code: 'TN',
    continent: 'Africa',
  },
  {
    name: 'Turkey',
    dialCode: '+90',
    code: 'TR',
    continent: 'Asia',
  },
  {
    name: 'Turkmenistan',
    dialCode: '+993',
    code: 'TM',
    continent: 'Asia',
  },
  {
    name: 'Turks and Caicos Islands',
    dialCode: '+1649',
    code: 'TC',
    continent: 'North America',
  },
  {
    name: 'Tuvalu',
    dialCode: '+688',
    code: 'TV',
    continent: 'Oceania',
  },
  {
    name: 'Uganda',
    dialCode: '+256',
    code: 'UG',
    continent: 'Africa',
  },
  {
    name: 'Ukraine',
    dialCode: '+380',
    code: 'UA',
    continent: 'Europe',
  },
  {
    name: 'United Arab Emirates',
    dialCode: '+971',
    code: 'AE',
    continent: 'Asia',
  },
  {
    name: 'United Kingdom',
    dialCode: '+44',
    code: 'GB',
    continent: 'Europe',
  },

  {
    name: 'Uruguay',
    dialCode: '+598',
    code: 'UY',
    continent: 'South America',
  },
  {
    name: 'Uzbekistan',
    dialCode: '+998',
    code: 'UZ',
    continent: 'Asia',
  },
  {
    name: 'Vanuatu',
    dialCode: '+678',
    code: 'VU',
    continent: 'Oceania',
  },
  {
    name: 'Venezuela, Bolivarian Republic of Venezuela',
    dialCode: '+58',
    code: 'VE',
    continent: 'South America',
  },
  {
    name: 'Vietnam',
    dialCode: '+84',
    code: 'VN',
    continent: 'Asia',
  },
  {
    name: 'Virgin Islands, British',
    dialCode: '+1284',
    code: 'VG',
    continent: 'North America',
  },
  {
    name: 'Virgin Islands, U.S.',
    dialCode: '+1340',
    code: 'VI',
    continent: 'North America',
  },
  {
    name: 'Wallis and Futuna',
    dialCode: '+681',
    code: 'WF',
    continent: 'Oceania',
  },
  {
    name: 'Yemen',
    dialCode: '+967',
    code: 'YE',
    continent: 'Asia',
  },
  {
    name: 'Zambia',
    dialCode: '+260',
    code: 'ZM',
    continent: 'Africa',
  },
  {
    name: 'Zimbabwe',
    dialCode: '+263',
    code: 'ZW',
    continent: 'Africa',
  },
] as const;

// Workaround to create a constant array
export type TCountryNames = (typeof countries)[number]['name'];
export const countryNames: [TCountryNames, ...TCountryNames[]] = [
  countries[0].name,
  ...countries.slice(1).map(({ name }) => name),
];

export function getCountryFlag(code = 'US') {
  return `https://flagsapi.com/${code}/flat/64.png`;
}

export function getCountryNameFromCode(code: string) {
  return countries.find((country) => country.code === code)?.name;
}

export function getDialCodeFromCountryCode(code: string) {
  return countries.find((country) => country.code === code)?.dialCode;
}

export function getCountryDetailsFromCode(code: string) {
  return countries.find((country) => country.code === code);
}
