export enum QueryKeys {
  LOGGED_IN_USER = 'logged-in-user',
  USER = 'user',
  PROPERTIES = 'properties',
  PROFILE = 'profile',
  INVESTMENTS = 'investments',
  MY_STAKES = 'my-stakes',
  TOTAL_INVESTED = 'total-invested',
  LISTINGS = 'listings',
  VAULT = 'vault',
  OWNED_PROPERTIES = 'owned-properties',
  USER_APPROVED_RENTAL_PROPERTIES = 'user-approved-rental-properties',
  APPROVED_WITHDRAWALS = 'approved-withdrawals',
  APPLICATIONS = 'applications',
  MONTHLY_RETURNS = 'monthly-returns',

  ALL_WITHDRAWAL_REQUESTS = 'all-withdrawal-requests',
  USER_WITHDRAWAL_REQUESTS = 'user-withdrawal-requests',

  EXPORT_MONTHLY_RETURNS = 'export-monthly-returns',
  RENTAL_INCOME_BALANCE = 'rental-income-balance',
  REFERRALS = 'referrals',
  RENTAL_PROPERTIES = 'rental-properties',
  ADMIN_RENTAL_PROPERTIES = 'admin-rental-properties',
  RENTAL_PROPERTY_CITIES = 'rental-property-cities',
  RENTAL_PROPERTY_STATES = 'rental-property-states',
  HAS_APPROVED_INVESTMENT = 'has-approved-investment',
  ADMIN_DASHBOARD_STATS = 'admin-dashboard-stats',
  USER_MEMBERSHIP_STATUS = 'user-membership-status',
  MEMBERSHIP_ACTIVATIONS = 'membership-activations',
  ADMIN_MEMBERSHIP_ACTIVATIONS = 'admin-membership-activations',
  ADMIN_NOTIFICATION = 'admin-notification',
  EXIT_WINDOWS = 'exit-windows',
  APP_SETTINGS = 'app-settings',
}
